/* Portriga — alle Übersetzungen.
   Bewusst als JavaScript und nicht als JSON: so kommen sie mit einem normalen
   <script>-Tag herein. Kein fetch, kein MIME-Typ, kein Ärger mit dem Cache.

   Eine Sprache ergänzen: einen vorhandenen Block kopieren, das Kürzel ändern
   und übersetzen. Die Schlüssel links und die Platzhalter in geschweiften
   Klammern bleiben unverändert. In der Auswahlliste erscheinen automatisch
   alle Länder, deren Sprache hier vorhanden ist — mehr ist nicht zu tun. */

const SPRACHEN = {
"de": {
  "kopf.augenbraue": "Allgäuer Stichspiel · Punkteblock",
  "a11y.lang": "Sprache wählen",
  "lang.title": "Sprache",
  "lang.search": "Land oder Sprache suchen",
  "allg.zurueck": "Zurück",
  "allg.speichern": "Speichern",
  "allg.bitteWaehlen": "– bitte wählen –",
  "setup.neuerSpieler": "Neuen Spieler anlegen",
  "setup.namePh": "Name",
  "setup.anlegen": "Anlegen",
  "setup.anzahl": "Anzahl der Spieler",
  "setup.anzahlPh": "z. B. 4",
  "setup.start": "Spiel starten",
  "setup.statistik": "Spielerstatistik",
  "setup.bearbeiten": "Bearbeiten",
  "setup.regeln": "Regeln",
  "setup.einrichtung": "Einrichtung",
  "setup.teilen": "Teilen",
  "setup.spielerN": "Spieler {n}",
  "setup.speicherwarnung": "Dieser Browser erlaubt kein dauerhaftes Speichern. Die Partie funktioniert, aber die Daten sind nach dem Schließen des Tabs weg.",
  "fuss.text": "Punkte werden nur in diesem Browser gespeichert.",
  "msg.nameEingeben": "Bitte einen Namen eingeben.",
  "msg.gibtEsSchon": "„{name}“ gibt es schon.",
  "msg.angelegt": "„{name}“ angelegt.",
  "msg.jedemNamen": "Bitte für jeden Spieler einen Namen auswählen.",
  "msg.nurEinmal": "Jeder Spieler darf nur einmal ausgewählt werden.",
  "msg.gueltigeZahlen": "Bitte gültige Zahlen eingeben.",
  "msg.summeStiche": "Summe der Stiche muss {noetig} sein (aktuell {summe}).",
  "msg.linkKopiert": "Link kopiert!",
  "msg.teilenText": "Portriga: der Punkteblock für das Kartenspiel Portriga.",
  "spiel.ansage": "Ansage",
  "spiel.stiche": "Stiche",
  "spiel.runde": "Runde {r} / {max}",
  "spiel.karteEine": "1 Karte",
  "spiel.kartenViele": "{n} Karten",
  "spiel.abschliessen": "Runde abschließen",
  "spiel.korrigieren": "Letzte Runde korrigieren",
  "ende.titel": "Spiel beendet",
  "ende.verlauf": "Punkteverlauf",
  "ende.verlaufA11y": "Punkteverlauf über alle Runden",
  "ende.historie": "Historie",
  "ende.historieSub": "Ansage / Stiche / Punkte",
  "ende.partieStatistik": "Statistik dieser Partie",
  "ende.neuesSpiel": "Neues Spiel",
  "ende.sieger": "Sieger",
  "ende.partieStatText": "{name}: {prozent}% richtig angesagt, {null}× Null angesagt",
  "ende.spalteRunde": "R",
  "stat.titel": "Spielerstatistik",
  "stat.highscore": "Highscore",
  "stat.highscoreWert": "{name} mit {punkte} Punkten",
  "stat.keineSpieler": "Noch keine Spieler angelegt.",
  "stat.spieler": "Spieler",
  "stat.spiele": "Spiele",
  "stat.avgPunkte": "Ø Pkt/Spiel",
  "stat.avgPlatz": "Ø Platz",
  "stat.legende": "Ø Platz ist genormt: 0 = im Schnitt immer Platz 1, 1 = im Schnitt immer letzter Platz. So bleiben Partien mit unterschiedlicher Spieleranzahl vergleichbar. Tippe auf einen Spieler, um alle seine Partien im Detail zu sehen.",
  "stat.keinePartien": "Noch keine Partien gespielt.",
  "stat.platzVon": "Platz {platz} / {anzahl}",
  "stat.punkte": "{punkte} Punkte",
  "stat.siegerPartie": "Sieger dieser Partie",
  "stat.rueckstand": "{punkte} Punkte Rückstand auf Platz 1",
  "stat.gegner": "Gegner: {liste}",
  "bearb.titel": "Bearbeiten",
  "bearb.spielerLoeschen": "Spieler löschen",
  "bearb.spielerLoeschenText": "Erscheint in alten Partien als „Gelöschter Spieler“",
  "bearb.spielerBearbeiten": "Spieler bearbeiten",
  "bearb.spielerBearbeitenText": "Namen ändern",
  "bearb.spielBearbeiten": "Spiel bearbeiten",
  "bearb.spielBearbeitenText": "Endpunkte, Datum und Uhrzeit ändern",
  "bearb.spielLoeschen": "Spiel löschen",
  "bearb.spielLoeschenText": "Verschwindet aus allen Statistiken",
  "bearb.sicherung": "Datensicherung",
  "bearb.sicherungText": "Die Partien liegen nur in diesem Browser. Sicherung herunterladen, um sie auf ein anderes Gerät zu übertragen.",
  "bearb.export": "Sicherung speichern",
  "bearb.import": "Sicherung laden",
  "bearb.spielerWaehlen": "Spieler auswählen",
  "bearb.partieWaehlen": "Partie auswählen",
  "bearb.neuerName": "Neuer Name",
  "bearb.partieLoeschen": "Partie löschen",
  "bearb.datum": "Datum",
  "bearb.uhrzeit": "Uhrzeit",
  "bearb.endpunkte": "Endpunkte",
  "fehler.spielerWaehlen": "Bitte einen Spieler auswählen.",
  "fehler.partieWaehlen": "Bitte eine Partie auswählen.",
  "fehler.partieZuerst": "Bitte zuerst eine Partie auswählen.",
  "fehler.punktzahl": "Bitte für alle Spieler eine gültige Punktzahl eingeben.",
  "warn.titel": "Sicherheitsabfrage",
  "warn.ja": "Ja, wirklich",
  "warn.nein": "Abbrechen",
  "frage.spielerLoeschen": "Soll der Spieler „{name}“ wirklich gelöscht werden? Er wird in bisherigen Partien fortan als „Gelöschter Spieler“ angezeigt, erscheint nicht mehr in der Statistik-Übersicht und steht für neue Partien nicht mehr zur Auswahl.",
  "frage.umbenennen": "Soll „{alt}“ wirklich in „{neu}“ umbenannt werden?",
  "frage.spielLoeschen": "Soll die Partie „{partie}“ wirklich gelöscht werden? Alle Statistiken werden neu berechnet.",
  "frage.spielAendern": "Sollen die Änderungen an der Partie „{partie}“ wirklich gespeichert werden? Plätze und Statistiken werden neu berechnet.",
  "regeln.titel": "Regeln",
  "regeln.h1": "Worum es geht",
  "regeln.p1": "Portriga ist das Allgäuer Stichspiel für 3 bis 10 Spieler. Jeder schätzt zu Beginn jeder Runde sein Blatt ein und sagt an, wie viele Stiche er gewinnen wird. Wer richtig liegt, bekommt Pluspunkte – wer daneben liegt, Minuspunkte.",
  "regeln.h2": "Karten",
  "regeln.p2": "Gespielt wird mit dem deutschen Blatt zu 36 Karten je Farbe (6, 7, 8, 9, 10, Unter, Ober, König, Ass). Bis zu fünf Spieler reicht ein Kartenspiel, ab sechs Spielern kommt ein zweites dazu.",
  "regeln.h3": "Ablauf einer Partie",
  "regeln.p3": "Eine Partie dauert 15 Runden. Die Anzahl der Karten pro Spieler steigt von Runde zu Runde: 1, 2, 3 … bis 7. Mit 7 Karten wird insgesamt dreimal gespielt, danach geht es wieder rückwärts bis auf 1 Karte. Nach jeder Runde wandert der Geber im Uhrzeigersinn weiter.",
  "regeln.h4": "Trumpf",
  "regeln.p4": "Nachdem der Geber ausgeteilt hat, wird die oberste Karte des Reststapels aufgedeckt. Ihre Farbe ist für diese Runde Trumpf.",
  "regeln.h5": "Ansage",
  "regeln.p5": "Beginnend beim Spieler links vom Geber sagt reihum jeder an, wie viele Stiche er mit seinem Blatt gewinnen kann. Auch „null“ ist erlaubt. Die Summe aller Ansagen muss nicht mit der Anzahl der gespielten Karten übereinstimmen.",
  "regeln.h6": "Stiche spielen",
  "regeln.p6": "Der Spieler links vom Geber spielt die erste Karte aus. Alle anderen müssen die angespielte Farbe bedienen. Wer das nicht kann, muss – sofern vorhanden – mit Trumpf stechen, andernfalls darf eine beliebige Karte abgeworfen werden. Den Stich gewinnt die höchste Karte der angespielten Farbe oder der höchste Trumpf. Werden mit zwei Kartenspielen gleiche Karten ausgespielt, zählt die zuerst gespielte höher.",
  "regeln.h7": "Punkte",
  "regeln.p7": "Am Ende jeder Runde wird verglichen, ob die Ansage erfüllt wurde:",
  "regeln.li1": "Ansage erfüllt: 10 Punkte plus 3 Punkte pro Stich. Wer z. B. 3 Stiche angesagt und gemacht hat, bekommt 19 Punkte; bei einer Ansage von 0 sind es 10 Punkte.",
  "regeln.li2": "Ansage verfehlt: 3 Minuspunkte für jeden Stich Differenz – egal ob zu viele oder zu wenige Stiche gemacht wurden.",
  "regeln.h8": "Spielende",
  "regeln.p8": "Nach 15 Runden gewinnt, wer die meisten Punkte gesammelt hat.",
  "einr.titel": "Einrichtung",
  "einr.intro": "Leg Portriga auf den Startbildschirm. Dann öffnet sich der Punkteblock mit einem Fingertipp und ohne Browserleiste, genau wie eine installierte App.",
  "einr.introDone": "Portriga liegt schon auf deinem Startbildschirm. Hier steht, wie es auf einem weiteren Gerät geht.",
  "einr.ios": "iPhone",
  "einr.android": "Android",
  "einr.desktop": "Rechner",
  "einr.ios1": "Diese Seite in <b>Safari</b> öffnen.",
  "einr.ios2": "Unten auf das <b>Teilen-Symbol</b> tippen, das Quadrat mit dem Pfeil nach oben.",
  "einr.ios3": "In der Liste nach unten wischen zu <b>Zum Home-Bildschirm</b>.",
  "einr.ios4": "Namen bestätigen und rechts oben <b>Hinzufügen</b> tippen.",
  "einr.iosNote": "Andere Browser als Safari können auf dem iPhone keine Verknüpfung anlegen.",
  "einr.android1": "Diese Seite in <b>Chrome</b> öffnen.",
  "einr.android2": "Oben rechts auf die <b>drei Punkte</b> tippen.",
  "einr.android3": "<b>App installieren</b> wählen, je nach Version heißt es <b>Zum Startbildschirm hinzufügen</b>.",
  "einr.android4": "Mit <b>Installieren</b> bestätigen.",
  "einr.androidNote": "Danach liegt Portriga wie eine App im App-Umschalter, mit eigenem Symbol.",
  "einr.desktop1": "Diese Seite in <b>Chrome</b> oder <b>Edge</b> öffnen.",
  "einr.desktop2": "Rechts in der Adresszeile auf das <b>Installieren-Symbol</b> klicken.",
  "einr.desktop3": "Mit <b>Installieren</b> bestätigen.",
  "einr.desktop4": "Portriga startet danach in einem eigenen Fenster.",
  "einr.desktopNote": "Am Rechner bleibt der Punkteblock damit ein Klick in der Taskleiste.",
  "einr.install": "Jetzt installieren",
  "fehler.speichern": "Fehler beim Speichern.",
  "fehler.datumZeit": "Bitte Datum und Uhrzeit angeben.",
  "bearb.exportOk": "Sicherung heruntergeladen.",
  "bearb.importOk": "Sicherung geladen.",
  "bearb.importFehler": "Datei konnte nicht gelesen werden."
},
"en": {
  "kopf.augenbraue": "Allgäu trick-taking game · score pad",
  "a11y.lang": "Choose language",
  "lang.title": "Language",
  "lang.search": "Search country or language",
  "allg.zurueck": "Back",
  "allg.speichern": "Save",
  "allg.bitteWaehlen": "– please choose –",
  "setup.neuerSpieler": "Add a new player",
  "setup.namePh": "Name",
  "setup.anlegen": "Add",
  "setup.anzahl": "Number of players",
  "setup.anzahlPh": "e.g. 4",
  "setup.start": "Start game",
  "setup.statistik": "Player statistics",
  "setup.bearbeiten": "Edit",
  "setup.regeln": "Rules",
  "setup.einrichtung": "Setup",
  "setup.teilen": "Share",
  "setup.spielerN": "Player {n}",
  "setup.speicherwarnung": "This browser does not allow permanent storage. The game works, but the data is gone once you close the tab.",
  "fuss.text": "Scores are stored in this browser only.",
  "msg.nameEingeben": "Please enter a name.",
  "msg.gibtEsSchon": "“{name}” already exists.",
  "msg.angelegt": "“{name}” added.",
  "msg.jedemNamen": "Please pick a name for every player.",
  "msg.nurEinmal": "Each player can only be picked once.",
  "msg.gueltigeZahlen": "Please enter valid numbers.",
  "msg.summeStiche": "The tricks must add up to {noetig} (currently {summe}).",
  "msg.linkKopiert": "Link copied.",
  "msg.teilenText": "Portriga: the score pad for the card game Portriga.",
  "spiel.ansage": "Bid",
  "spiel.stiche": "Tricks",
  "spiel.runde": "Round {r} of {max}",
  "spiel.karteEine": "1 card",
  "spiel.kartenViele": "{n} cards",
  "spiel.abschliessen": "Finish round",
  "spiel.korrigieren": "Correct last round",
  "ende.titel": "Game over",
  "ende.verlauf": "Points over time",
  "ende.verlaufA11y": "Points across all rounds",
  "ende.historie": "History",
  "ende.historieSub": "bid / tricks / points",
  "ende.partieStatistik": "About this game",
  "ende.neuesSpiel": "New game",
  "ende.sieger": "Winner",
  "ende.partieStatText": "{name}: {prozent}% bids met, bid zero {null}×",
  "ende.spalteRunde": "R",
  "stat.titel": "Player statistics",
  "stat.highscore": "High score",
  "stat.highscoreWert": "{name} with {punkte} points",
  "stat.keineSpieler": "No players yet.",
  "stat.spieler": "Player",
  "stat.spiele": "Games",
  "stat.avgPunkte": "Avg pts/game",
  "stat.avgPlatz": "Avg place",
  "stat.legende": "Avg place is normalised: 0 means always first on average, 1 means always last. That keeps games with different player counts comparable. Tap a player to see all their games in detail.",
  "stat.keinePartien": "No games played yet.",
  "stat.platzVon": "Place {platz} of {anzahl}",
  "stat.punkte": "{punkte} points",
  "stat.siegerPartie": "Won this game",
  "stat.rueckstand": "{punkte} points behind first place",
  "stat.gegner": "Opponents: {liste}",
  "bearb.titel": "Edit",
  "bearb.spielerLoeschen": "Delete player",
  "bearb.spielerLoeschenText": "Shows up in old games as “Deleted player”",
  "bearb.spielerBearbeiten": "Edit player",
  "bearb.spielerBearbeitenText": "Change the name",
  "bearb.spielBearbeiten": "Edit game",
  "bearb.spielBearbeitenText": "Change final scores, date and time",
  "bearb.spielLoeschen": "Delete game",
  "bearb.spielLoeschenText": "Disappears from every statistic",
  "bearb.sicherung": "Backup",
  "bearb.sicherungText": "Your games live in this browser only. Download a backup to move them to another device.",
  "bearb.export": "Save backup",
  "bearb.import": "Load backup",
  "bearb.spielerWaehlen": "Choose a player",
  "bearb.partieWaehlen": "Choose a game",
  "bearb.neuerName": "New name",
  "bearb.partieLoeschen": "Delete game",
  "bearb.datum": "Date",
  "bearb.uhrzeit": "Time",
  "bearb.endpunkte": "Final scores",
  "fehler.spielerWaehlen": "Please choose a player.",
  "fehler.partieWaehlen": "Please choose a game.",
  "fehler.partieZuerst": "Please choose a game first.",
  "fehler.punktzahl": "Please enter a valid score for every player.",
  "warn.titel": "Are you sure?",
  "warn.ja": "Yes, do it",
  "warn.nein": "Cancel",
  "frage.spielerLoeschen": "Really delete the player “{name}”? From now on they appear in past games as “Deleted player”, no longer show up in the statistics overview and cannot be picked for new games.",
  "frage.umbenennen": "Really rename “{alt}” to “{neu}”?",
  "frage.spielLoeschen": "Really delete the game “{partie}”? Every statistic will be recalculated.",
  "frage.spielAendern": "Really save the changes to the game “{partie}”? Places and statistics will be recalculated.",
  "regeln.titel": "Rules",
  "regeln.h1": "What it is",
  "regeln.p1": "Portriga is the trick-taking game from the Allgäu, for 3 to 10 players. At the start of every round each player sizes up their hand and bids how many tricks they will win. Get it right and you score; get it wrong and you lose points.",
  "regeln.h2": "Cards",
  "regeln.p2": "Played with the German deck of 36 cards, nine per suit (6, 7, 8, 9, 10, Under, Over, King, Ace). Up to five players one deck is enough; from six players a second one joins.",
  "regeln.h3": "How a game runs",
  "regeln.p3": "A game lasts 15 rounds. The number of cards per player rises round by round: 1, 2, 3 … up to 7. Seven cards are played three times in total, then it goes back down to a single card. After each round the deal passes clockwise.",
  "regeln.h4": "Trumps",
  "regeln.p4": "Once the dealer has dealt, the top card of the remaining stack is turned over. Its suit is trumps for that round.",
  "regeln.h5": "Bidding",
  "regeln.p5": "Starting to the dealer's left, each player in turn says how many tricks their hand can win. Zero is allowed. The bids do not have to add up to the number of cards in play.",
  "regeln.h6": "Playing the tricks",
  "regeln.p6": "The player to the dealer's left leads. Everyone else must follow suit. Anyone who cannot must trump if they hold one, otherwise any card may be discarded. The trick goes to the highest card of the suit led, or the highest trump. When two decks put identical cards on the table, the one played first ranks higher.",
  "regeln.h7": "Scoring",
  "regeln.p7": "At the end of each round the bid is compared with the tricks taken:",
  "regeln.li1": "Bid met: 10 points plus 3 points per trick. Bid three and take three, and that is 19 points; a bid of zero that holds is 10 points.",
  "regeln.li2": "Bid missed: 3 penalty points for every trick of difference, whether too many or too few.",
  "regeln.h8": "End of the game",
  "regeln.p8": "After 15 rounds, whoever has collected the most points wins.",
  "einr.titel": "Setup",
  "einr.intro": "Put Portriga on your home screen. The score pad then opens with one tap and without a browser bar, just like an installed app.",
  "einr.introDone": "Portriga is already on your home screen. Here is how to do it on another device.",
  "einr.ios": "iPhone",
  "einr.android": "Android",
  "einr.desktop": "Computer",
  "einr.ios1": "Open this page in <b>Safari</b>.",
  "einr.ios2": "Tap the <b>share icon</b> at the bottom, the square with the arrow.",
  "einr.ios3": "Scroll down the list to <b>Add to Home Screen</b>.",
  "einr.ios4": "Confirm the name and tap <b>Add</b> in the top right.",
  "einr.iosNote": "On iPhone, browsers other than Safari cannot create the shortcut.",
  "einr.android1": "Open this page in <b>Chrome</b>.",
  "einr.android2": "Tap the <b>three dots</b> in the top right.",
  "einr.android3": "Choose <b>Install app</b>, older versions call it <b>Add to Home screen</b>.",
  "einr.android4": "Confirm with <b>Install</b>.",
  "einr.androidNote": "Portriga then sits in the app switcher like any app, with its own icon.",
  "einr.desktop1": "Open this page in <b>Chrome</b> or <b>Edge</b>.",
  "einr.desktop2": "Click the <b>install icon</b> on the right of the address bar.",
  "einr.desktop3": "Confirm with <b>Install</b>.",
  "einr.desktop4": "Portriga then runs in its own window.",
  "einr.desktopNote": "On a computer the score pad is one click away in the taskbar.",
  "einr.install": "Install now",
  "fehler.speichern": "Could not save.",
  "fehler.datumZeit": "Please give a date and a time.",
  "bearb.exportOk": "Backup downloaded.",
  "bearb.importOk": "Backup loaded.",
  "bearb.importFehler": "The file could not be read."
}
};
